-- Create dedicated application user and grant privileges
-- IMPORTANT: Do not use SYSTEM schema for application tables.

WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- Variables (edit if you change ENV names)
-- Using literals as this runs inside container init

-- Switch to target PDB
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER TM_APP IDENTIFIED BY tm_app_password
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO TM_APP;
GRANT CREATE TABLE TO TM_APP;
GRANT CREATE SEQUENCE TO TM_APP;
GRANT CREATE VIEW TO TM_APP;
GRANT CREATE PROCEDURE TO TM_APP;
GRANT CREATE TRIGGER TO TM_APP;
GRANT UNLIMITED TABLESPACE TO TM_APP;

EXIT;
